import { integer, index, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const loanApplications = sqliteTable(
  "loan_applications",
  {
    id: text("id").primaryKey(),
    answersJson: text("answers_json").notNull(),
    status: text("status", { enum: ["pending", "approved"] })
      .notNull()
      .default("pending"),
    panDocumentKey: text("pan_document_key").notNull(),
    panDocumentName: text("pan_document_name").notNull(),
    panDocumentType: text("pan_document_type").notNull(),
    aadhaarDocumentKey: text("aadhaar_document_key").notNull(),
    aadhaarDocumentName: text("aadhaar_document_name").notNull(),
    aadhaarDocumentType: text("aadhaar_document_type").notNull(),
    aadhaarFrontDocumentKey: text("aadhaar_front_document_key"),
    aadhaarFrontDocumentName: text("aadhaar_front_document_name"),
    aadhaarFrontDocumentType: text("aadhaar_front_document_type"),
    aadhaarBackDocumentKey: text("aadhaar_back_document_key"),
    aadhaarBackDocumentName: text("aadhaar_back_document_name"),
    aadhaarBackDocumentType: text("aadhaar_back_document_type"),
    faceVideoKey: text("face_video_key"),
    faceVideoName: text("face_video_name"),
    faceVideoType: text("face_video_type"),
    faceVerifiedAt: text("face_verified_at"),
    approvedAmount: integer("approved_amount"),
    bankDetailsJson: text("bank_details_json"),
    disbursementSubmittedAt: text("disbursement_submitted_at"),
    processingFeeAmount: integer("processing_fee_amount"),
    paymentUpiId: text("payment_upi_id"),
    paymentQrKey: text("payment_qr_key"),
    paymentQrName: text("payment_qr_name"),
    paymentQrType: text("payment_qr_type"),
    feePaidMarkedAt: text("fee_paid_marked_at"),
    loanTransferredAt: text("loan_transferred_at"),
    approvalTitle: text("approval_title").notNull().default(""),
    approvalImageKey: text("approval_image_key"),
    approvalImageName: text("approval_image_name"),
    approvalImageType: text("approval_image_type"),
    createdAt: text("created_at").notNull(),
    reviewedAt: text("reviewed_at"),
  },
  (table) => [index("idx_loan_applications_status_created").on(table.status, table.createdAt)],
);
